### Raiz
POST https://cfgateway.casaid.workers.dev/
Content-Type: application/json

{
  "message": "simples"
}

### Async
POST https://cfgateway.casaid.workers.dev/async/40
Content-Type: application/json

{
  "methodDestiny": "GET",
  "destiny": "https://github.com/frkr",
  "callback": "https://cfgateway.casaid.workers.dev/store/41"
}

