### Raiz
POST https://cfgateway.casaid.workers.dev/
Content-Type: application/json

{
  "message": "simples"
}

### Async
POST https://cfgateway.casaid.workers.dev/async/66
Content-Type: application/json
Authorization: Bearer change_me_in_production

{
  "methodDestiny": "GET",
  "destiny": "https://github.com/frkr",
  "callback": "https://cfgateway.casaid.workers.dev/store/67"
}

### Path novo
POST https://cfgateway.casaid.workers.dev/davi
Content-Type: application/json

{
  "message": "Teste125"
}
