POST https://cfgateway.casaid.workers.dev/async/11
Content-Type: application/json

{
  "destiny": "https://github.com/frkr",
  "callback": "https://cfgateway.casaid.workers.dev/store/12",
  "method": "GET"
}